### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mediaproduction** [vijuSR/facial_emotion_recognition__EMOJIFIER#9]
please help me

(venv) root@kali:~/facial_emotion_recognition__EMOJIFIER# python3 src/dataset_creator.py
[2019-01-01 19:06:15] [root] [INFO] (Loggers ready !)
  0%|                                                                                                    | 0/5 [00:00<?, ?it/s][2019-01-01 19:06:15] [emojifier.dataset_creator] [DEBUG] (length images list: 0)

Traceback (most recent call last):
  File "src/dataset_creator.py", line 151, in <module>
    _images, _labels = image_label_generator()
  File "src/dataset_creator.py", line 47, in image_label_generator
    images = image_reader(image_list)
  File "src/dataset_creator.py", line 16, in image_reader
    image = cv2.imread(image_path_list[0], 0)
IndexError: list index out of range

**Comment by vijuSR** [comment]
This line in your error "0%| | 0/5 [00:00<?, ?it/s][2019-01-01 19:06:15] [emojifier.dataset_creator] [DEBUG] **(length images list: 0)**" suggests that it didn't find any images at the set path for the images directory.
Did you capture the images? Can you please check, the images if captured are in the right directory?

**Comment by mediaproduction** [comment]
The captured images in images folder. I created 2 folder one is cry another happy. 
Each folder have 200 captured images.

Step 1 : is successfully completed

problem in Step : 2

can you solve this

**Comment by vijuSR** [comment]
There is a problem with the emotions (folder names) that you mentioned. You can only create emotion classes that are defined [**here**](https://github.com/vijuSR/facial_emotion_recognition__EMOJIFIER/blob/4e3c9c3c2d92208bd2932a8e105f4b6c095f5821/src/dataset_creator.py#L143). Change this dict as you want but only create (**all**)the emotions mentioned in the dict. 

This was something that needed a mention in the getting started section. Will do it. Thanks.

**Comment by vijuSR** [comment]
@mediaproduction, give it one more try.
